//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CafeDemo.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderPosition
    {
        public int Id { get; set; }
        public int OrderId { get; set; }
        public int PositionId { get; set; }
        public bool IsReady { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual Position Position { get; set; }
    }
}
