//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CafeDemo.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Position
    {
        public Position()
        {
            this.OrderPosition = new HashSet<OrderPosition>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int PositionTypeId { get; set; }
        public string Photo { get; set; }
    
        public virtual ICollection<OrderPosition> OrderPosition { get; set; }
        public virtual PositionType PositionType { get; set; }
    }
}
